# Generated by Django 5.0.6 on 2024-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="gender",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="college",
            name="unknown",
            field=models.CharField(max_length=100),
        ),
    ]
